version: '3.2'

services:
  app:
    build:
      context: node
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  webserver:
    image: nginx:latest
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/html:/var/www/html
      - ./log:/var/log/nginx/
    depends_on:
      - app
    networks:
      - node-network
    links:
      - app

networks:
  node-network:
    driver: bridge
